adjust-cell-width = 5%
adjust-cell-height = 10%

background = #141414

cursor-color = #00ff94
cursor-style = block

font-family = Monaco
font-size = 13
font-style = Regular
# only on MacOS
font-thicken = true
# disable ligatures
font-feature = -calt, -liga, -dlig

shell-integration-features = no-cursor

# theme = Kolorit
